"""drop username unique

Revision ID: 518904f716ab
Revises: 78c2fb95adbb
Create Date: 2026-03-07 19:06:33.874085

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '518904f716ab'
down_revision: Union[str, Sequence[str], None] = '78c2fb95adbb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_users_username'), table_name='users')
    op.create_index(op.f('ix_users_users_username'), 'users', ['username'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_users_username'), table_name='users')
    op.create_index(op.f('ix_users_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###
