"""add external_task_id to generation

Revision ID: 56d7950d4277
Revises: e7a2f1b3c4d5
Create Date: 2026-03-12 20:53:59.681260

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56d7950d4277'
down_revision: Union[str, Sequence[str], None] = 'e7a2f1b3c4d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('generations', sa.Column('external_task_id', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('generations', 'external_task_id')
    # ### end Alembic commands ###
