"""cascade delete, drop version_id from users

Revision ID: baa77c6a8411
Revises: 9a7740c33627
Create Date: 2026-03-07 19:30:27.390862

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'baa77c6a8411'
down_revision: Union[str, Sequence[str], None] = '9a7740c33627'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_generations_user_id_users'), 'generations', type_='foreignkey')
    op.create_foreign_key(op.f('fk_generations_user_id_users'), 'generations', 'users', ['user_id'], ['user_id'], ondelete='CASCADE')
    op.drop_constraint(op.f('fk_purchases_user_id_users'), 'purchases', type_='foreignkey')
    op.create_foreign_key(op.f('fk_purchases_user_id_users'), 'purchases', 'users', ['user_id'], ['user_id'], ondelete='CASCADE')
    op.drop_constraint(op.f('fk_referrals_referrer_id_users'), 'referrals', type_='foreignkey')
    op.drop_constraint(op.f('fk_referrals_referred_id_users'), 'referrals', type_='foreignkey')
    op.create_foreign_key(op.f('fk_referrals_referrer_id_users'), 'referrals', 'users', ['referrer_id'], ['user_id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_referrals_referred_id_users'), 'referrals', 'users', ['referred_id'], ['user_id'], ondelete='CASCADE')
    op.drop_constraint(op.f('fk_useractions_user_id_users'), 'useractions', type_='foreignkey')
    op.create_foreign_key(op.f('fk_useractions_user_id_users'), 'useractions', 'users', ['user_id'], ['user_id'], ondelete='CASCADE')
    op.drop_constraint(op.f('fk_userbalances_user_id_users'), 'userbalances', type_='foreignkey')
    op.create_foreign_key(op.f('fk_userbalances_user_id_users'), 'userbalances', 'users', ['user_id'], ['user_id'], ondelete='CASCADE')
    op.drop_column('users', 'version_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('version_id', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=False))
    op.drop_constraint(op.f('fk_userbalances_user_id_users'), 'userbalances', type_='foreignkey')
    op.create_foreign_key(op.f('fk_userbalances_user_id_users'), 'userbalances', 'users', ['user_id'], ['user_id'])
    op.drop_constraint(op.f('fk_useractions_user_id_users'), 'useractions', type_='foreignkey')
    op.create_foreign_key(op.f('fk_useractions_user_id_users'), 'useractions', 'users', ['user_id'], ['user_id'])
    op.drop_constraint(op.f('fk_referrals_referred_id_users'), 'referrals', type_='foreignkey')
    op.drop_constraint(op.f('fk_referrals_referrer_id_users'), 'referrals', type_='foreignkey')
    op.create_foreign_key(op.f('fk_referrals_referred_id_users'), 'referrals', 'users', ['referred_id'], ['user_id'])
    op.create_foreign_key(op.f('fk_referrals_referrer_id_users'), 'referrals', 'users', ['referrer_id'], ['user_id'])
    op.drop_constraint(op.f('fk_purchases_user_id_users'), 'purchases', type_='foreignkey')
    op.create_foreign_key(op.f('fk_purchases_user_id_users'), 'purchases', 'users', ['user_id'], ['user_id'])
    op.drop_constraint(op.f('fk_generations_user_id_users'), 'generations', type_='foreignkey')
    op.create_foreign_key(op.f('fk_generations_user_id_users'), 'generations', 'users', ['user_id'], ['user_id'])
    # ### end Alembic commands ###
