"""add_include_admins_to_mailings

Revision ID: d165b429f075
Revises: 4f8e3ce4549d
Create Date: 2026-03-12 13:02:49.613734

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd165b429f075'
down_revision: Union[str, Sequence[str], None] = '4f8e3ce4549d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mailings', sa.Column('include_admins', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mailings', 'include_admins')
    # ### end Alembic commands ###
